config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include('polls.urls')),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

polls/urls.py
from django.urls import path, include
from .views import QuestionListView, PostDetailView, QuestionCreateView, ChoiceCreateView, QuestionUpdateView, QuestionDeleteView
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:question_id>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/practice/", views.Practice.as_view(), name="practice"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('questions/', QuestionListView.as_view(), name='question_list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('question/new/', QuestionCreateView.as_view(), name='question_new'),
    path('question/<int:pk>/choice/new/', ChoiceCreateView.as_view(), name='choice_new'),
    path('question/<int:pk>/update/', QuestionUpdateView.as_view(), name='question_update'),
    path('question/<int:pk>/delete/', QuestionDeleteView.as_view(), name='question_delete'),
    path('homepage/', views.HomePageView.as_view(), name='home'),
    
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    def length_print(self):
        return len(self.question_text)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


from datetime import date

from django.db import models


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField(default=date.today)
    authors = models.ManyToManyField(Author)
    number_of_comments = models.IntegerField(default=0)
    number_of_pingbacks = models.IntegerField(default=0)
    rating = models.IntegerField(default=5)

    def __str__(self):
        return self.headline

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import F
from django.utils import timezone
from django.http import HttpResponse
from django.template import loader
from .models import Post
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Choice, Question
from django.views.generic.list import ListView



"""
주소 : 판교 , 네이버, 백엔드 부서로 -> 택배를 보낸다.
주소 : 주소확인 -> 우체국 -> 다리 건너서
-> 네이버 본사 -> 백엔드로 배달이 된다.
"""

# Create your views here.


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :9
        ]
        # return Question.objects.filter(pk=1)


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_object(self): 
        # kwargs['urls.py 패턴값과 같음']
        q_id = self.kwargs['question_id']
        question = get_object_or_404(Question, pk=q_id)
        return question

    # def get_queryset(self):
    #     """
    #     Return the last five published questions (not including those set to be
    #     published in the future).
    #     """
    #     return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")
    
    
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


class Practice(generic.DetailView):
    model = Question
    template_name = "polls/practice.html"


class QuestionListView(ListView):
    model = Question
    template_name = 'polls/question_list.html'  # 사용할 템플릿 파일 지정
    context_object_name = 'question_list'  # 템플릿에서 사용할 변수 이름 지정

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]

    def get_object(self): 
        # kwargs['urls.py 패턴값과 같음']
        q_id = self.kwargs['question_id']
        question = get_object_or_404(Question, pk=q_id)
        return question


class PostDetailView(DetailView):
    model = Post
    template_name = 'polls/post_detail.html'  # 사용할 템플릿 파일 지정
    context_object_name = 'post'  # 템플릿에서 사용할 변수 이름 지정


class QuestionCreateView(CreateView):
    model = Question
    fields = ['question_text']
    template_name = 'polls/question_form.html'
    success_url = reverse_lazy('polls:index')  # 예시 URL, 실제 프로젝트에 맞게 수정 필요


class ChoiceCreateView(CreateView):
    model = Choice
    fields = ['choice_text']
    template_name = 'polls/choice_form.html'

    def form_valid(self, form):
        form.instance.question = get_object_or_404(Question, pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('polls:detail', kwargs={'question_id': self.kwargs['pk']})
    

class QuestionUpdateView(UpdateView):
    model = Question
    fields = ['question_text', 'pub_date']
    template_name = 'polls/update_question_form.html'  # 재사용하거나 적절한 템플릿 지정
    success_url = reverse_lazy('polls:index')  # 예시 URL, 실제 프로젝트에 맞게 수정 필요


class QuestionDeleteView(DeleteView):
    model = Question
    template_name = 'polls/question_confirm_delete.html'
    success_url = reverse_lazy('polls:index')  # 삭제 후 리다이렉션될 URL, 실제 프로젝트에 맞게 수정 필요

# ==================================

from django.views.generic.base import TemplateView

from polls.models import Question


class HomePageView(TemplateView):
    template_name = "polls/practice.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["latest_articles"] = Question.objects.all()[:5]
        return context

polls/templates/polls/choice_form.html
<h1>Add a new choice</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Choice</button>
</form>

polls/templates/polls/detail.html
<!-- <h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul> -->
<!-- <h3>{{question.id}}</h3>
<h3>{{question.question_text}}</h3>
<h3>{{question.pub_date}}</h3>
<h3>{{question.choice_set.all.0}}</h3>
<h3>{{question.choice_set.all.0.votes}}</h3>
<h3>{{question.choice_set.all.count}}</h3> -->
<!-- <h3>{{question.pub_date|date:"Y M D"}}</h3>
<h3>{{question.id}}</h3>
<h3>{{question.question_text}}</h3>
<h3>{{question.choice_set.all.1.choice_text|title }}</h3> -->


<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Polls App</title>
</head>


<body>


    {% if latest_question_list %}

    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}

</body>

</html>

polls/templates/polls/post_detail.html
<body>
    <h1>{{ post.title }}</h1>
    <p>Published on: {{ post.published_date }}</p>
    <div>
        {{ post.content }}
    </div>
</body>

polls/templates/polls/practice.html
<!-- {% if latest_articles %}

<ul>
    {% for question in latest_articles %}
    <li>{{ question.question_text}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->


{% if latest_articles %}

<ul>
    {% for question in latest_articles %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/question_confirm_delete.html
<h1>Are you sure you want to delete "{{ object.question_text }}"?</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
    <a href="{% url 'polls:index' %}">Cancel</a>
</form>

polls/templates/polls/question_form.html
<h1>New Question</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Question</button>
</form>

polls/templates/polls/question_list.html
<ul>
    {% for question in question_list %}
    <li>{{ question.question_text }}</li>
    {% endfor %}
</ul>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/update_question_form.html
<h1>Update Question</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Question</button>
</form>